In [1]:
import pandas as pd

In [8]:
data = pd.read_csv("car.csv")

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   car_ID            205 non-null    int64  
 1   symboling         205 non-null    int64  
 2   CarName           205 non-null    object 
 3   fueltype          205 non-null    object 
 4   aspiration        205 non-null    object 
 5   doornumber        205 non-null    object 
 6   carbody           205 non-null    object 
 7   drivewheel        205 non-null    object 
 8   enginelocation    205 non-null    object 
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64  
 14  enginetype        205 non-null    object 
 15  cylindernumber    205 non-null    object 
 16  enginesize        205 non-null    int64  
 1

In [17]:
X = data.iloc[:,8:13].values

In [11]:
y = data.iloc[:,-1].values

In [18]:
X


array([['front', 88.6, 168.8, 64.1, 48.8],
       ['front', 88.6, 168.8, 64.1, 48.8],
       ['front', 94.5, 171.2, 65.5, 52.4],
       ...,
       ['front', 109.1, 188.8, 68.9, 55.5],
       ['front', 109.1, 188.8, 68.9, 55.5],
       ['front', 109.1, 188.8, 68.9, 55.5]], dtype=object)

In [16]:
y

array([13495.   , 16500.   , 16500.   , 13950.   , 17450.   , 15250.   ,
       17710.   , 18920.   , 23875.   , 17859.167, 16430.   , 16925.   ,
       20970.   , 21105.   , 24565.   , 30760.   , 41315.   , 36880.   ,
        5151.   ,  6295.   ,  6575.   ,  5572.   ,  6377.   ,  7957.   ,
        6229.   ,  6692.   ,  7609.   ,  8558.   ,  8921.   , 12964.   ,
        6479.   ,  6855.   ,  5399.   ,  6529.   ,  7129.   ,  7295.   ,
        7295.   ,  7895.   ,  9095.   ,  8845.   , 10295.   , 12945.   ,
       10345.   ,  6785.   ,  8916.5  ,  8916.5  , 11048.   , 32250.   ,
       35550.   , 36000.   ,  5195.   ,  6095.   ,  6795.   ,  6695.   ,
        7395.   , 10945.   , 11845.   , 13645.   , 15645.   ,  8845.   ,
        8495.   , 10595.   , 10245.   , 10795.   , 11245.   , 18280.   ,
       18344.   , 25552.   , 28248.   , 28176.   , 31600.   , 34184.   ,
       35056.   , 40960.   , 45400.   , 16503.   ,  5389.   ,  6189.   ,
        6669.   ,  7689.   ,  9959.   ,  8499.   , 

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [23]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')

In [22]:
import numpy as np

In [25]:
X = np.array(ct.fit_transform(X))

In [27]:
X

array([[0.0, 1.0, 0.0, ..., 168.8, 64.1, 48.8],
       [0.0, 1.0, 0.0, ..., 168.8, 64.1, 48.8],
       [0.0, 1.0, 0.0, ..., 171.2, 65.5, 52.4],
       ...,
       [0.0, 1.0, 0.0, ..., 188.8, 68.9, 55.5],
       [0.0, 1.0, 0.0, ..., 188.8, 68.9, 55.5],
       [0.0, 1.0, 0.0, ..., 188.8, 68.9, 55.5]], dtype=object)

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [30]:
from sklearn.linear_model import LinearRegression

In [31]:
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [32]:
y_pred = regressor.predict([X_test[5]])

In [33]:
y_pred

array([13670.78495002487], dtype=object)